version: '3'
services:
  redis:
    image: redis:6.2.4
    container_name: sonezaki_redis

  base: &base
    image: sonezaki
    working_dir: /home/app/app
    volumes:
      - .:/home/app/app

  base_build:
    <<: *base
    build: .
    command: echo done

  sonezaki:
    <<: *base
    container_name: sonezaki
    depends_on: [base_build]
    command: /bin/bash -c 'rspec'
    env_file: .env

  test_all:
    <<: *base
    depends_on: [base_build]
    command: /bin/bash -c 'rspec && yard && rake yardstick_measure && rake verify_measurements'
